---
# tasks file for patch_update
- name: Update the systems
  block:
    - name: Run yum update
      yum:
        name: tmux
        state: present
      register: update_results

    - name: If successful, add to succeeded list
      set_stats:
        data:
          report_success: "{{ report_success + [{
                     'SUCCESS': inventory_hostname,
                     'Updated': update_results.changed }] }}"

  rescue:

    - name: If failed, add to failed list
      set_stats:
        data:
          report_failed: "{{ report_failed + [{
                  'FAILED': inventory_hostname,
                  'failure': ansible_failed_result.msg }] }}"

  always:
    - name: Create list of connection failures
      set_stats:
        data:
          connect_fail_list: "{{ ansible_play_hosts_all | difference(ansible_play_batch) | join('\n') }}"
      delegate_to: localhost
      run_once: true