---
# tasks file for patch_report
- name: Create the report
  set_fact:
    report_out:
      failed: "{{ report_failed }}"
      succeeded: "{{ report_success }}"

- name: Send email report
  mail:
    subject: Patching Report for {{ lookup('pipe', 'date') }}
    host: 192.168.1.218
    port: 25
    to: Tech2734 <tech2734@gmail.com>
    body: |
          This is a test
          Failure report:
          {{ report_out | to_nice_yaml }}
    from: Root <root@tower1.local.jmb>
  delegate_to: localhost