---
# tasks file for patch_report
- name: Create the report
  set_fact:
    report_out:
      failed: "{{ report_failed }}"
      succeeded: "{{ report_success }}"

- name: Send email report
  mail:
    subject: Patching Report for {{ lookup('pipe', 'date') }}
    host: "{{ report_mailhost }}"
    port: "{{ report_mailport }}"
    to: "{{ report_mailto }}"
    body: |
          Patching Results Report:
          <pre>{{ report_out | to_nice_yaml }}</pre>
          The following had connection or other issues:
          {{ connect_fail_list }}
    from: "{{ report_mailfrom }}"
    subtype: html
  delegate_to: localhost
  run_once: true