---
# tasks file for patch_report
- name: Create the report
  set_fact:
    report_out: |
              Systems that failed patching:
              {{ report_failed | to_nice_yaml }}

              Systems that successfully patched:
              {{ report_success | to_nice_yaml }}
              
- name: Send email report
  mail:
    subject: Patching Report for {{ lookup('pipe', 'date') }}
    host: 192.168.1.218
    port: 25
    to: Tech2734 <tech2734@gmail.com>
    body: |
          This is a test
          Failure report:
          {{ report_out | to_nice_yaml }}
    from: Root <root@tower1.local.jmb>
  delegate_to: localhost