---
# tasks file for patch_report
- name: Create the report
  set_fact:
    report_out:
      failed: "{{ report_failed }}"
      succeeded: "{{ report_success }}"

- name: Send email report
  mail:
    subject: Patching Report for {{ lookup('pipe', 'date') }}
    host: "{{ report_mailhost }}"
    port: "{{ report_mailport }}"
    to: "{{ report_mailto }}"
    body: |
          Patching Results Report:
          {{ report_out | to_nice_yaml }}
    from: "{{ report_mailfrom }}"
  delegate_to: localhost
  run_once: true